spring:
  application:
    name: taskmanager

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    locations: classpath:db/migration

jwt:
  expiration: ${JWT_EXPIRATION:86400000}